### ISSUE TITLE
Animation for "Big" Wins

### ISSUE THREAD

**Issue by CourtneyAhaus** [nhabbott/Poker#1]
List of Wins from smallest to largest:
Pair 
Three of a kind 
Straight (cards in a row)
Flush (cards of same suit)
Full House (one pair and one three of a kind)
Four of a Kind
Straight Flush (Five cards in a row of the same suit)
Royal Flush (Five Cards AKQJ and 10 of same suit)

**Comment by CourtneyAhaus** [comment]
Do we want it to rotate inside of a circle with the amount of money? or just want the words to display and count the amount of money?

**Comment by CourtneyAhaus** [comment]
public boolean isFlush() {
 String suit = hand.get(0).getSuit();
for(int i = 1; i < 5; i++) {
   if(!suit.equals(hand.get(i).getSuit())) { 
return false;
)
return true;
}

something like this?

**Comment by CourtneyAhaus** [comment]
private boolean countKind(int findNum) { 
   for(int kind = 0; kind < Deck.NUMBER_OF_CARDS_IN_STANDARD_SUIT; kind++) {
       int kindCount = 0;
         for (int i = 0; i < 5; i++) {
            if (hand.get(i).getValue()==kind) {
              kindCount++; 
         }
         if (kindCount==findNum) {
            return true;
         }
         return false;
}
public boolean isFourOfAKind() {
     return countKind(4);
)
public boolean isThreeOfAKind() {
     return countKind(3);
}

something like this for 3 and 4 of a kind

**Comment by CourtneyAhaus** [comment]
public class Card {
private String suit;
private int value;

public Card(int value, String suit) {
 this.value = value;
 this.suit = suit;
}

public int getValue() {
   return value;
}
public String getSuit() {
return suit;
}

public String toString() {
String theValue = "";
if (value == 11) 
theValue = "Jack"
else if (value ==12)
theValue = "Queen"
else if (value ==13)
theValue = "King"
else if (value ==14)
theValue = "Ace"
else theValue = String.valueOf(value);
return theValue + " of " + suit;
}

**Comment by CourtneyAhaus** [comment]
this was my black jack from CS1 if we can use parts of the code lets do it =)

import java.util.Scanner;
public class CourtneyAhausHomework6 {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);
		
		int [] deck = new int [52];

		boolean done = false;
		
	
		for (int i = 0; i < deck.length; i++) {
			deck [i] = i;
		}
			int [] newDeck = shuffleDeck(deck);
			int i = 0;
			while ( !done) {
				int[] playerHand =  {newDeck[i], newDeck[i+1]};
				int[] dealerHand = { newDeck[i+2], newDeck[i+3]};
				i += 4;
				System.out.print("Your hand is the ");
				name(playerHand[0]);
				System.out.print(" and the ");
				name(playerHand[1]);
				System.out.println();
				int y = assignCard(playerHand[0]) + assignCard(playerHand[1]);
				System.out.println("Value: " + y);
				System.out.println();
				System.out.print("The dealers hand is ");
				name(dealerHand[0]);
				System.out.print(" and the ");
				name(dealerHand[1]);
				int d = assignCard(dealerHand[0]) + assignCard(dealerHand[1]);
				System.out.println();
				System.out.println("Value: " + d);
				compareHands(playerHand, dealerHand);
				System.out.println("Done? Y/N: ");
				String answer = input.nextLine();
				if (answer.contains("y")){
					done = true;
				}
			}
	}
			//COMPARING HANDS
			private static void compareHands(int [] you, int[] computer) {
				int y = assignCard(you[0]) + assignCard(you[1]);
				int d = assignCard(computer[0]) + assignCard(computer[1]);
				System.out.println();
				if (y > d) {
					System.out.println("You won!");
				}
				else if (y < d) {
					System.out.println("You lost!");
				}
				else if (y == d) {
					System.out.println("You tied!");
				}
			}
			//SHUFFLE DECK
			private static int [] shuffleDeck(int [] deck) {
				for (int i = 0; i < 1000; i++) {
					int a =(int)(Math.random()*100) % 52;
					int b =(int)(Math.random()*100) % 52;
					int temp = deck[a];
					deck[a] = deck[b];
					deck[b] = temp;
				}
				return deck;
			}
			//ASSIGNING CARDS
			private static int assignCard(int card) {
				int value = 0;
		
			switch (card % 13) {
				case 0: 
					if (value == 11) {
						value += 1;
					}
					else if (value < 11) {
						value = 11;
					} 					break;
				case 1: value += 2; 	break;
				case 2: value += 3; 	break;
				case 3: value += 4; 	break;
				case 4: value += 5; 	break;
				case 5: value += 6; 	break;
				case 6: value += 7; 	break;
				case 7: value += 8; 	break;
				case 8: value += 9; 	break;
				case 9: value += 10; 	break;
				case 10: value += 11; 	break;
				case 11: value += 12; 	break;
				case 12: value += 13; 	break;
				}
				return value;
			}
			private static void name (int card) {
				switch (card % 13) {
					case 0: System.out.print("Ace of "); 	break;
					case 1: System.out.print("Two of "); 	break;
					case 2: System.out.print("Three of "); 	break;
					case 3: System.out.print("Four of "); 	break;
					case 4: System.out.print("Five of "); 	break;
					case 5: System.out.print("Six of "); 	break;
					case 6: System.out.print("Seven of "); 	break;
					case 7: System.out.print("Eight of "); 	break;
					case 8: System.out.print("Nine of "); 	break;
					case 9: System.out.print("Ten of "); 	break;
					case 10: System.out.print("Jack of "); 	break;
					case 11: System.out.print("Queen of "); break;
					case 12: System.out.print("King of "); 	break;
				}
				switch (card / 13) {
					case 0: System.out.print("Spades"); 	break;
					case 1: System.out.print("Hearts"); 	break;
					case 2: System.out.print("Diamonds"); 	break;
					case 3: System.out.print("Clubs"); 		break;
				}			

	}

}

**Comment by nhabbott** [comment]
I like the circle idea.

**Comment by CourtneyAhaus** [comment]
a circle and spin text one time pop it out and put it back in the circle.

**Comment by nhabbott** [comment]
This will be done with a single function that returns a SequentialTransition. Determining whether or not the win is big should be done when giving the reward.
`bigWinAnimation(circle: Node, text: Node): SequentialTransition`
